Make the CSV export buttons consistent, and hide the HTML export buttons
BirkbeckCTP/imports pull request #61
Opened 2022-04-05 15:09 UTC by joemull

Fixes #59

2022-04-05 15:40 UTC, mauromsl requested changes
Cheers @joemull , a couple of comments in-line

2022-04-05 15:40 UTC, mauromsl commented on views.py
> +        articles = submission_models.Article.objects.filter(pk=article_id)
This should also filter by `request.journal` where available to avoid cross-journal  attacks

2022-04-06 09:38 UTC, joemull commented on templates/import/articles_all.html
> +                                <input type="hidden" class="tiny secondary button" type="submit" name="article_id" value="{{article.pk}}">
Ah good catch. I'll remove type="submit".

Yes, I used a button element in addition--I wanted to preserve the icon in the content of the button, and the input's value attribute would have interfered with that, I believe.

2022-04-06 09:46 UTC, mauromsl approved these changes

2022-04-06 09:46 UTC, merged